/**
 * ClinicCard — a clickable clinic result rendered inside a chat message.
 * Tapping navigates to the code-minted booking deep link and closes the chat.
 */
import { useNavigate } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Building2, MapPin, ArrowRight } from "lucide-react";
import type { ClinicCardItem } from "@queuemed/core";

interface ClinicCardProps {
  item: ClinicCardItem;
  onNavigate?: () => void;
}

export function ClinicCard({ item, onNavigate }: ClinicCardProps) {
  const navigate = useNavigate();
  const go = () => {
    onNavigate?.();
    // bookingHref is code-generated by @queuemed/core (e.g. /booking/:clinicId).
    navigate(item.bookingHref);
  };

  return (
    <Card
      role="button"
      tabIndex={0}
      onClick={go}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          go();
        }
      }}
      className="cursor-pointer p-3 transition-shadow hover:shadow-md"
    >
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <div className="flex items-center gap-1.5 text-sm font-medium text-gray-900">
            <Building2 className="h-4 w-4 shrink-0 text-blue-600" />
            <span className="truncate">{item.name}</span>
          </div>
          {item.specialty && <p className="mt-0.5 text-xs text-gray-600">{item.specialty}</p>}
          {item.city && (
            <p className="mt-0.5 flex items-center gap-1 text-xs text-gray-500">
              <MapPin className="h-3 w-3" />
              {item.city}
            </p>
          )}
        </div>
        <ArrowRight className="h-4 w-4 shrink-0 text-gray-400" />
      </div>
    </Card>
  );
}
