export const CONSULTATION_ERROR_CODES = {
  UNEXPECTED: 'CONSULTATION_UNEXPECTED_ERROR',
  DIAGNOSIS_LABEL_REQUIRED: 'CONSULTATION_DIAGNOSIS_LABEL_REQUIRED',
  MEDICATION_NAME_REQUIRED: 'CONSULTATION_MEDICATION_NAME_REQUIRED',
  TEST_NAME_REQUIRED: 'CONSULTATION_TEST_NAME_REQUIRED',
  CONTEXT_MISSING_APPOINTMENT: 'CONSULTATION_CONTEXT_MISSING_APPOINTMENT',
  CONTEXT_MISSING_PATIENT: 'CONSULTATION_CONTEXT_MISSING_PATIENT',
  CONTEXT_STALE: 'CONSULTATION_CONTEXT_STALE',
  CONFLICT_RELOAD: 'CONSULTATION_CONFLICT_RELOAD',
  NOTES_CONFLICT_RELOAD: 'CONSULTATION_NOTES_CONFLICT_RELOAD',
} as const;

export type ConsultationErrorCode =
  (typeof CONSULTATION_ERROR_CODES)[keyof typeof CONSULTATION_ERROR_CODES];
